# Generated by Django 3.2 on 2023-04-15 11:24

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('directory', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Demand',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('diplom_type', models.PositiveSmallIntegerField(choices=[(1, 'Общая'), (2, 'Теория'), (3, 'Практика')], default=1)),
                ('language', models.PositiveSmallIntegerField(choices=[(1, 'Казахский'), (2, 'Русский'), (3, 'Английский')], default=1)),
                ('subject', models.CharField(max_length=250)),
                ('deadline', models.DateField()),
                ('comment', models.TextField()),
                ('is_archive', models.BooleanField(default=False)),
                ('is_distribution', models.BooleanField(default=True)),
                ('is_expert_selected', models.BooleanField(default=False)),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('type_task', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='directory.typetask')),
            ],
        ),
        migrations.CreateModel(
            name='DemandFile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.FileField(upload_to='demand_files')),
                ('date', models.DateField(auto_now_add=True)),
                ('demand', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='task_management.demand')),
            ],
        ),
        migrations.CreateModel(
            name='DemandDistribution',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(auto_now_add=True)),
                ('status', models.PositiveSmallIntegerField(choices=[(1, 'Ожидание'), (2, 'Отклик'), (3, 'Ожидание оплаты'), (4, 'Заказ принят'), (5, 'Заказ оплачено')], default=1)),
                ('price', models.DecimalField(blank=True, decimal_places=0, max_digits=10, null=True)),
                ('prepayment', models.DecimalField(blank=True, decimal_places=0, max_digits=5, null=True)),
                ('comment', models.TextField(blank=True, null=True)),
                ('phone_number', models.CharField(blank=True, max_length=20, null=True)),
                ('is_expert_selected', models.BooleanField(default=False)),
                ('demand', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='task_management.demand')),
                ('expert', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='DemandCompletedFile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(blank=True, max_length=250, null=True)),
                ('file', models.FileField(upload_to='demand_completed_files')),
                ('date', models.DateField(auto_now_add=True)),
                ('demand', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='task_management.demand')),
            ],
        ),
    ]
