# Generated by Django 4.1 on 2023-01-30 11:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('task_management', '0007_alter_demand_is_distribution'),
    ]

    operations = [
        migrations.AlterField(
            model_name='demanddistribution',
            name='price',
            field=models.DecimalField(blank=True, decimal_places=0, max_digits=10, null=True),
        ),
    ]
